server:
  port: 8081
  address: 10.38.16.184
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/HelpEaseProApp?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: a15987255470
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid

#自定义配置文件
#上传视频本地保存地址
videoSavePath: /Users/soanr/Desktop/videos
